[WIP]feature/DAF-3938
dwango-nfc/betterplayer pull request #14
Opened 2023-04-24 09:32 UTC by mayumiishiyama

## Description
Fixed to show PIP if the app is closed while playing a video.

### Problem
The process of automatic PIP when the application is closed is not implemented.

### Solution
code fix

### What was done (Please be a little bit specific)

- Fixed PIP to be ready for display when video playback starts
- Fixed to discard the state of PIP when playback is stopped.

## Reference
### JIRA
https://dw-ml-nfc.atlassian.net/browse/DAF-3938

## Screenshot or Video (Before/After)

2023-04-25 07:39 UTC, noboru-i requested changes
@mayumiishiyama 
すいません、質問などコメントしています。ご確認ください :bow:

（note: PIP状態でアプリを開いた場合の制御は、 https://dw-ml-nfc.atlassian.net/browse/DAF-3942 として別チケット対応）

2023-04-25 07:39 UTC, noboru-i commented on example/lib/pages/picture_in_picture_page.dart
> +      handleLifecycle: false,
すいません、一度 `feature/pip` ブランチの内容を取り込んでいただきたいです。

https://github.com/dwango-nfc/betterplayer/pull/13 がマージされたので、この差分は出なくなるはず、、、です :bow:

2023-04-25 07:39 UTC, noboru-i commented on ios/Classes/BetterPlayer.m
> +- (void)preparePictureInPicture: (CGRect) frame
memo:
Copy from `usePlayerLayer` and modify.

(`usePlayerLayer` is never used. Because we don't call `enablePictureInPicture`.)

2023-04-25 07:39 UTC, noboru-i commented on ios/Classes/BetterPlayer.m
> +            _pipController = [[AVPictureInPictureController alloc] initWithPlayerLayer: playerLayer];
すいません、確認です。

以前は `self._playerLayer` を渡していたようですが、今回 `self._betterPlayerView.playerLayer` に変えた理由は何でしょうか？

2023-04-25 08:43 UTC, mayumiishiyama commented on ios/Classes/BetterPlayer.m
> +            _pipController = [[AVPictureInPictureController alloc] initWithPlayerLayer: playerLayer];
正直、行き詰まってる時に大城さんが参考にシェアしてくれたコードで`self._betterPlayerView.playerLayer`に修正されていたので試しに同じように修正したら動いたからってのが理由なんですけど...`self._playerLayer`は何度か更新されるのでそれだとうまく動かないのかなぁと。ボタン押してのPIPは元のコードでも動くんですけど、自動でPIPにするのだとダメなんですよね。。

2023-04-25 08:44 UTC, mayumiishiyama commented on example/lib/pages/picture_in_picture_page.dart
> +      handleLifecycle: false,
マージしました！

2023-04-25 09:00 UTC, noboru-i commented on ios/Classes/BetterPlayer.m
> +            _pipController = [[AVPictureInPictureController alloc] initWithPlayerLayer: playerLayer];
https://github.com/dwango-nfc/betterplayer/commit/93a093cf9401471bd22b9bea9591480528d799ad#diff-4b6db25e7cbbc0e1b666cb708e68032d43c6e1ca72216f387e89d0dfc254ca3eR650
この部分ですかね。

@HiroshiOshiro 
気になっただけ、ではあるのですが、
こちら何故変えたか覚えていますか？

2023-04-26 01:48 UTC, HiroshiOshiro reviewed
@noboru-i 
返答しました。

@mayumiishiyama 
コメントしてます。既存コードが謎なのですみませんが、確認したいです。

2023-04-26 01:48 UTC, HiroshiOshiro commented on ios/Classes/BetterPlayer.m
> +            _pipController = [[AVPictureInPictureController alloc] initWithPlayerLayer: playerLayer];
@noboru-i 
既存コード（usePlayerLayerで`self._playerLayer` を作成し、ここで使っている）の理由がわからず、またPIPにした時に画面上に動画が複製される原因になっているようでした。

https://user-images.githubusercontent.com/4166369/234439460-10853ffe-a290-4275-b31e-a61477d29825.mov

今回[チュートリアル](https://developer.apple.com/documentation/avkit/adopting_picture_in_picture_in_a_custom_player?language=objc)に沿う形で_payerのAVPlayerLayer をそのまま使うようにした。

という形です。

2023-04-26 01:48 UTC, HiroshiOshiro commented on ios/Classes/BetterPlayer.m
> +        }
この追加って必要です？
コード的には
_pipControllerをnilにして直後に作り直す。いうことになると思うので。

おそらくこのコード、PIPから復帰した時に、すぐまたPIPになってしまう。ことを防ぐためな気はしますが、
（既存のコードなので謎なんですが）すぐ上にある
```
[self setPictureInPicture:true];
```
をコメントアウトしてみるとどうでしょうか

2023-04-26 01:56 UTC, noboru-i commented on ios/Classes/BetterPlayer.m
> +            _pipController = [[AVPictureInPictureController alloc] initWithPlayerLayer: playerLayer];
@HiroshiOshiro 
ありがとうございます！

@mayumiishiyama 
PRのdescription部分に、 https://developer.apple.com/documentation/avkit/adopting_picture_in_picture_in_a_custom_player?language=objc のチュートリアルのリンクを追加しておいてください 🙏

2023-04-26 02:26 UTC, mayumiishiyama commented on ios/Classes/BetterPlayer.m
> +        }
@HiroshiOshiro 
>PIPから復帰した時に、すぐまたPIPになってしまう。ことを防ぐため

PIPを閉じた時に動画が止まったまま動かなくなってしまうのを防ぎたくて入れたコードになります。
`[self setPictureInPicture:true];`をコメントアウトしても動いたのでとりあえずこっちは削除しておきました。

2023-04-26 03:20 UTC, mayumiishiyama commented on ios/Classes/BetterPlayer.m
> +            _pipController = [[AVPictureInPictureController alloc] initWithPlayerLayer: playerLayer];
@noboru-i 
追加しました🙇

2023-04-26 03:24 UTC, noboru-i approved these changes
別タスクの中で変わる部分もあるかと思うので、一旦LGTMとします。
（処理の流れが理解しきれてない部分もありますが）

@HiroshiOshiro 
確認いただき、問題なければ Approve いただけますか？
（それをもって、VN確認に回そうと思います。）

2023-04-26 03:33 UTC, HiroshiOshiro reviewed
とりあえず、動いてる前提でApprove。

2023-04-26 03:33 UTC, HiroshiOshiro approved these changes

2023-04-26 03:45 UTC, noboru-i commented
@mvn-thanhluu-hn 
Please review this PR. 🙏

2023-04-26 03:56 UTC, mvn-thanhluu-hn approved these changes
LGTM.

2023-04-26 04:46 UTC, merged