DAF-4255 - Inactive seek button while watching livestream in PiP mode
dwango-nfc/betterplayer pull request #40
Opened 2023-07-31 07:07 UTC by mvn-hienvu-hn

updating...

2023-08-01 08:06 UTC, mvn-thanhluu-hn reviewed
@mvn-hienvu-hn 
Sorry, please check my comments 🙏

2023-08-01 08:06 UTC, mvn-thanhluu-hn commented on ios/Classes/BetterPlayer.h
> +- (void)setIsHidedPipSeekButtons:(BOOL) isHided;
```suggestion
- (void)setPipSeekButtonsHidden:(BOOL) isHidden;
```

2023-08-01 08:06 UTC, mvn-thanhluu-hn commented on ios/Classes/BetterPlayerPlugin.m
> +            player._isLiveStream = isLiveStream;
We use `_` ofter for property only use in parent class, please make a set function for it.

2023-08-01 09:31 UTC, mvn-thanhluu-hn approved these changes
LGTM.

@mvn-hienvu-hn Thank you.

2023-08-02 01:12 UTC, HiroshiOshiro requested changes
I have a small request. please check it.
(Please update flutter repo too)

2023-08-02 01:12 UTC, HiroshiOshiro commented on lib/src/configuration/better_player_data_source.dart
> +    bool? liveStream,
Please change to `isLiveStream` (in all part)

2023-08-02 06:59 UTC, HiroshiOshiro approved these changes
LGTM

2023-08-02 07:03 UTC, merged