DAF-4473: [Android] When livestream is being archived, progress bar is still active in control center
dwango-nfc/betterplayer pull request #58
Opened 2023-10-20 07:33 UTC by mvn-hieunguyen-hn

## Description
[Android] When livestream is being archived, progress bar is still active in control center
### Problem
[Android] When livestream is being archived, progress bar is still active in control center
### Solution
create new flag to check disable seekbar
### What was done (Please be a little bit specific)

- create new flag to check disable seekbar
- create new logic check flag to add duration

## Reference
### JIRA
https://dw-ml-nfc.atlassian.net/browse/DAF-4473

### JP (and VN) Specs
None

### Figma
None

### API (Only for API implementation)
None

## Screenshot or Video (Before/After)
None

## Ready for review checklist
Basically, you must check all. (When you ignore any checks, please write each reason.)

- [x] All sections above are properly filled in
- [x] The PR only deals with one functionality/bug
- [x] The code include code refactoring? If yes, the following sub checks are required.
    - [x] The changes were tested. So there is no degradation.
    - [x] The change is not too big. (Reviewers can review it.)
- [x] Builds and runs on iOS (No new warnings nor new errors)
- [x] Builds and runs on Android (No new warnings nor new errors)

2023-10-25 07:03 UTC, mvn-thanhluu-hn approved these changes
LGTM

@mvn-hieunguyen-hn Thanks!
I have a small suggestion. Please check it 🙏

2023-10-25 07:03 UTC, mvn-thanhluu-hn commented on lib/src/configuration/better_player_data_source.dart
> +  final bool? isHideSeekbarNotification;
```suggestion
  ///Flag determine hide seekbar of notification. Currently only supported in Android platform.
  ///Fix bug ticket: https://dw-ml-nfc.atlassian.net/browse/DAF-4473
  final bool? isSeekbarOnNotificationDisable;
```

Please use document comment `///` and note this flag only for Android.

2023-10-25 07:33 UTC, mvn-thanhluu-hn commented
@noboru-i 
Please review this PR 🙏

2023-10-25 10:03 UTC, noboru-i requested changes
@mvn-hieunguyen-hn 
I add some comments. Please check it 🙏

2023-10-25 10:03 UTC, noboru-i commented on android/src/main/kotlin/com/jhomlala/better_player/BetterPlayer.kt
>                      // LIVE
I think, this comment is for `isCurrentMediaItemLive`.
How about removing this line?
Please check it 🙏

2023-10-25 10:03 UTC, noboru-i commented on android/src/main/kotlin/com/jhomlala/better_player/BetterPlayerPlugin.kt
> +        private var _notificationParameter: MutableLiveData<NotificationParameter?> =
Is this diff caused by formatter?
If so, please re-check whether other VN members also cause this diff or not.
(I'm afraid of rollback these changes by other member's format.)

2023-10-25 10:03 UTC, noboru-i commented on lib/src/configuration/better_player_data_source.dart
> +  ///Flag determine hide seekbar of notification. Currently only supported in Android platform.
Sorry.
iOS works OK...?
(It seems related to `isLiveStream`. We cannot use it?)

2023-10-26 04:34 UTC, mvn-hieunguyen-hn commented on android/src/main/kotlin/com/jhomlala/better_player/BetterPlayerPlugin.kt
> +        private var _notificationParameter: MutableLiveData<NotificationParameter?> =
I have checked with other VN members, and they also cause this difference. It's possible that the previous coder forgot to format the code.

2023-10-26 04:40 UTC, mvn-hieunguyen-hn commented on android/src/main/kotlin/com/jhomlala/better_player/BetterPlayer.kt
>                      // LIVE
@noboru-i 
When I checked the code, I found this variable, but I didn't see its clear meaning for case `Live Finished And Making Archive`. So, I added a new variable to make the code more explicit. I tried using variable `isCurrentMediaItemLive ` and found that the application worked well, so I deleted the new variable I had added.

2023-10-26 04:40 UTC, mvn-hieunguyen-hn commented on lib/src/configuration/better_player_data_source.dart
> +  ///Flag determine hide seekbar of notification. Currently only supported in Android platform.
@noboru-i 
When I checked the code, I found this variable, but I didn't see its clear meaning for case `Live Finished And Making Archive`. So, I added a new variable to make the code more explicit. I tried using variable `isCurrentMediaItemLive ` and found that the application worked well, so I deleted the new variable I had added.

2023-10-26 04:45 UTC, mvn-hieunguyen-hn commented
@noboru-i 
I have finished fixing your comments, please check them again for me, thanks  🙏

2023-10-26 06:32 UTC, noboru-i commented on android/src/main/kotlin/com/jhomlala/better_player/BetterPlayerPlugin.kt
> +        private var _notificationParameter: MutableLiveData<NotificationParameter?> =
OK, Thanks.
I understand. 👍

2023-10-26 06:35 UTC, noboru-i approved these changes
LGTM.

2023-10-26 06:43 UTC, merged